update Date option
yhoi/LINEBOT_booking_tennis pull request #1
Opened 2021-01-19 01:40 UTC by yhoi

時間取得を関数内で実行するようにgetUseYM()を変更しました。

2021-01-19 01:52 UTC, onefforts requested changes
一旦、指摘点のみ修正して反映よろしくー

2021-01-19 01:52 UTC, onefforts commented on server.js
> +        let date = new Date();
値が変わらないものについては `const` を使うよう統一すると良い

2021-01-19 01:52 UTC, onefforts commented on server.js
> +	var year = date.getFullYear();
`var` は古いバージョンでのjsでの定義方法なので今後は使わないようにしていこう

2021-01-19 01:52 UTC, onefforts commented on server.js
>  function getUseYM(){
YMだと何の略称なのかわからないため、Year & Monthにして良い。
あと `getUse~` の意味が伝わりにくいので名称を要検討

2021-01-19 01:52 UTC, onefforts commented on server.js
>  function Domeresult(headers){
関数名と変数名は js だと `camelCase` が一般的なのでそれで統一したい
https://qiita.com/suzuki-kei/items/97011c31a30e1bb74724

2021-01-19 02:26 UTC, yhoi commented
add_Dateのブランチの中に修正したfileのScheduleChecker.jsを作成しました。

2021-01-19 02:35 UTC, onefforts requested changes
細かい統一性部分を一旦指摘。ロジックについては後ほど指摘する。

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +    channelSecret: env.LINECHANNEL_SECRET,
細かいけどインデントが4のとこと2のとこで別れてるので2で統一して欲しいｗ

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +        let date = new Date();
ここはconstで良さそう

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +	let year = date.getFullYear();
ここはconstで良さそう

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +        let month = date.getMonth()+1;
ここはconstで良さそう

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +	let date = new Date();
ここはconstで良さそう

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +function getYear_Month(){
アンダースコアは無しでOK

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                        	"UseYM":  getUseYM(),
ここも略名じゃなくする

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                        	"UseYM": getUseYM(),
ここも略称じゃなくする

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +	let date = new Date();
let -> const

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +			let options ={
let -> const

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                        	let $ = cheerio.load(body);
let -> cosnt

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                        	let length = $('.koma-table').length;
let -> cosnt

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                                	if(i==8||i==20||i==13){
インデントを2に変更

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                                	let x = $('.koma-table').eq(i);
let -> cosnt

2021-01-19 02:35 UTC, onefforts commented on ScheduleChecker.js
> +                                        	let mark = $(x).find('td').eq(j).text();
let -> cosnt

2021-01-20 00:56 UTC, yhoi commented
ScheduleChecker.jsの修正完了しました。

2021-01-20 01:18 UTC, onefforts requested changes
命名規則についてはこういったドキュメントを参照して自分の中で妥当だと思うルールを持っておく。
https://murashun.jp/article/programming/naming-conventions.html

2021-01-20 01:18 UTC, onefforts commented on ScheduleChecker.js
> +function domeResult(headers){
`domeResult` & `parkResult` の処理で共通の部分があるので抽象化して統一する

2021-01-20 01:18 UTC, onefforts commented on ScheduleChecker.js
> +function getYearMonth(){
-> `getYearMonthString`　とかのほうが良さそう。getYearMonthだけだと何のために、どんなフォーマットのデータが来るかがわからない。

2021-01-20 01:18 UTC, onefforts commented on ScheduleChecker.js
> +function setHeaders(){
setHeaderの名前なら Headerをセットすること以外のことはやらないほうが良い。名前と処理の不一致でわかりにくくなるため。

2021-01-20 01:18 UTC, onefforts commented on ScheduleChecker.js
> +  const getHeaders = await setHeaders();
get~というのは同士なので変数には使わないほうが良い。

2021-01-20 01:18 UTC, onefforts commented on ScheduleChecker.js
> +        uri: "http://reserve.city.aizuwakamatsu.fukushima.jp/index.php",
URL等基本的なデータはプログラム上部で共通変数として定義して置く。マジックナンバーにはなるべくしない。

2021-01-20 02:51 UTC, yhoi commented on ScheduleChecker.js
> +        uri: "http://reserve.city.aizuwakamatsu.fukushima.jp/index.php",
マジックナンバーとは、何ですか？

2021-01-20 05:02 UTC, yhoi commented
修正したので確認お願い致します。

2021-01-20 05:50 UTC, yhoi commented
コメントの追加と関数や変数などの名前を変更しました。
確認お願いします。

2021-01-20 06:21 UTC, onefforts approved these changes
LGTM!

2021-01-20 06:23 UTC, merged