Add place・コーディング
yhoi/LINEBOT_booking_tennis pull request #3
Opened 2021-03-28 03:13 UTC by yhoi

ふれあいの予約状況をあらたに取得できるように変更しました。
コーディングをして頂けるとありがたいです

2021-03-28 14:19 UTC, onefforts requested changes
ふれあい追加ナイス！レビューしたので、確認よろしく〜

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +function getCourtOptions(headers,yearMonth,date){
getだとオプションをどこからか取ってくるように思えるから gen のままで良さそう

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +function getStringTimetable($,scrapingCourtNum,scrapingCourtSize,courtNum,courtNumSize){
ここの get も gen で良さそう。それか make とかかなー。String -> Textの方が良さそう。 table -> Table

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +    if(courtNumSize==3){
3がマジックナンバーになっているので、コードの最初の部分にFureaiCode = 3みたいに定義してやると、より読みやすい。

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +      if( k==18 || k==13 || k==25 || k==32|| k==35){
ここの数字もマジックナンバーになっているので、変数定義してわかりやすくしてやると良さそう。あと || が多いので `[18, 13, 25...].includes(number)`のように書いてやると短く書ける
参考: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +          const courtNum=1;
ココらへんもマジックナンバーを避けたい

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +	  const courtNum=1;
ココらへんもマジックナンバーを避けたい

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +	  let ScrapingCourtNum=7;
ココらへんもマジックナンバーを避けたい

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
> +	    if(ScrapingCourtSize == 11||ScrapingCourtSize == 16||ScrapingCourtSize ==25 ){
`Array.includes` で書きたい

2021-03-28 14:19 UTC, onefforts commented on ScheduleChecker.js
>  function dateConfirm(place){
return しているデータがobjectデータなので `genDateConfirmationObject` でいいかも。

2021-03-31 00:58 UTC, yhoi commented
レビューを反映させました。
確認お願いします。

2021-06-16 03:19 UTC, merged